version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - flask_network
    ports:
      - "3306:3306"

  app:
    build: ./backend/aggregator
    environment:
      MYSQL_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db
    depends_on:
      - db
    networks:
      - flask_network
    ports:
      - "5000:5000"

  userservice:
    build: ./backend/userservice
    environment:
      MYSQL_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db
    depends_on:
      - db
    networks:
      - flask_network
    ports:
      - "8000:5000"

  userclassservice:
    build: ./backend/userclassservice
    environment:
      MYSQL_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db
    depends_on:
      - db
    networks:
      - flask_network
    ports:
      - "8001:5000"

  skillmatchclassservice:
    build: ./backend/skillmatchclassservice
    environment:
      MYSQL_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db
    depends_on:
      - db
    networks:
      - flask_network
    ports:
      - "8002:5000"

volumes:
  mysql_data:

networks:
  flask_network:
    driver: bridge